[tasks.bad]
script = ["npx webpack-dev-server --config webpack.config.js"]

[tasks.good]
env = { CARGO_MAKE_SCRIPT_FORCE_PIPE_STDIN = true }
script = ["npx webpack-dev-server --config webpack.config.js"]